export type PIVOT_CONSTANTS = 'PIVOT_W' | 'PIVOT_SW' | 'PIVOT_SE' | 'PIVOT_S' |
    'PIVOT_NW' | 'PIVOT_NE' | 'PIVOT_N' | 'PIVOT_E' | 'PIVOT_CENTER';

export type ADJUST_CONSTANTS = 'ADJUST_FIT' | 'ADJUST_STRETCH' | 'ADJUST_ZOOM';

export type ANCHOR_CONSTANTS = 'ANCHOR_LEFT' | 'ANCHOR_BOTTOM' | 'ANCHOR_NONE' | 'ANCHOR_RIGHT' | 'ANCHOR_TOP';
export type PROP_CONSTANTS = 'PROP_SLICE9' | 'PROP_SIZE' | 'PROP_SHADOW' | 'PROP_SCALE' |
    'PROP_ROTATION' | 'PROP_POSITION' | 'PROP_OUTLINE' | 'PROP_INNER_RADIUS' | 'PROP_FILL_ANGLE' |
    'PROP_COLOR';